# Configuración de Samba - Compartición de Archivos

[compartidoCasioTech]
   path = /srv/samba/compartido
   browseable = yes
   writable = yes
   guest ok = yes
   create mask = 0777
   directory mask = 0777
