# 🌐 Configuración Global de Red - Casiopea Technology

# IPs de los Servidores
IP_DNS="192.168.1.111"
IP_DHCP="192.168.1.112"
IP_WEB="192.168.1.114"

# Rango DHCP
DHCP_RANGE_START="192.168.1.10"
DHCP_RANGE_END="192.168.1.100"

# Dominios y Nombres
DOMAIN="casio.local"
HOSTNAME_DNS="dns-server"
HOSTNAME_DHCP="dhcp-server"
HOSTNAME_WEB="web-server"

# Rutas de Backup
BACKUP_DIR="/backup/dhcpd_conf_backup"
RETENTION_DAYS=30
